let scriptId = ScriptApp.getScriptId();
Logger.log('El ID del script es: ' + scriptId);
//Configuracion desarrollo
if(scriptId=="1rhwbuxfWQi09QE6D00x_hzjFdQzeBtDT7g_lZS_d9zkKJdWRG1bioZCb"){

    FOLDER_IN_BBVA="1PQmMCoU3x4Z43CoTqa7ner7GGrikGahQ"
    FOLDER_OUT_BBVA="11zs0k8SW2ZhGZa1uqzFJWyFFpzWdr7M_"
    FOLDER_EXCEL="1bDniFyDnqufKI_XYz5jSGcDvJIvOCn3q"
    FOLDER_IN_BCP="18xF_-c-1AbS1hUdSEhjF9CJDu0ZqvH6h"
    FOLDER_OUT_BCP="1UG6U9b6t4ycIMFVHwga3EHMlne3eSBAM"
    ID_CONSOLIDADO="1JqsixcQyCiyStZzoar8JyTp-P05XoY9ikwb2RQhgzqc"
    PROCESS_ID="RPADEV_CANCELACIONES_REGISTRO_DE_INGRESO"
    CHILD_TABLE_ID="Table::CANCELACIONESFACTURAS_1"

    KEY_ID_PROCESS="KEY_ID_DEV"
    KEY_SECRET_PROCESS="KEY_SECRET_DEV"
    KEY_ID_DATASET="KEY_ID_DAFTES"
    KEY_SECRET_DATASET="KEY_SECRET_DAFTES"

    COMISION_DATASET_ID="DAFTES_DS_RI_COMISIONES_BBVA"
    CONCEPTOS_DATASET_ID="DB_RI_CONCEPTOS_COMPROBANTES_UNIDADES_1"

//Configuracion produccion
}else if(scriptId=="1Rc8DGlqniE1XuCULSsyCH_Pv_ACi_-M7a6NMkSZCh3T7sVBm15_GKr9J"){

    FOLDER_IN_BBVA="11_kULsreaRCZGkGV8J2GEovzJ-4GFmhQ"
    FOLDER_OUT_BBVA="1r_qoOJ-z1Ip-JgksxHX8FHjWqaSqH3RG"
    FOLDER_EXCEL="1yEk1AlaXzUYQ6jdPzmQ_DHyr__qUtZTo"
    FOLDER_IN_BCP="1VqIgAVqYCQgu_a7DOPsOYY0W3mq4DfQ7"
    FOLDER_OUT_BCP="1Cf-TH15VBQ6FCD7b8Hzk3KOe6Wih6tJi"
    ID_CONSOLIDADO="1ztv0T_ShQECssDSJaxaB3tu2l-RLmAjFgXqKhvFOgTk"
    PROCESS_ID="DEV_CANCELACIONES_SERVICIOS_VARIOS_REGIS"
    CHILD_TABLE_ID="Table::CANCELACIONESFACTURAS_1"

    KEY_ID_PROCESS="KEY_ID_DAFTES"
    KEY_SECRET_PROCESS="KEY_SECRET_DAFTES"
    KEY_ID_DATASET="KEY_ID_DAFTES"
    KEY_SECRET_DATASET="KEY_SECRET_DAFTES"

    COMISION_DATASET_ID="DAFTES_DS_RI_COMISIONES_BBVA"
    CONCEPTOS_DATASET_ID="DB_RI_CONCEPTOS_COMPROBANTES_UNIDADES_1"

}
